ci: add check-rustc job (#554)
* add check rustc job to CI

* fic typo in .yml

* remove name from .yml

* fix .yml indentation

* add verify install check

* add verifcation into single run command

* update run command

* fix .yml indentation typo

* add semver rustc

* update comment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,7 @@ env:
   RUSTFLAGS: -D warnings
   REGISTRY: ghcr.io
   SQLX_OFFLINE: true
+  RUSTC_VERSION: 1.67.0
 
 jobs:
   cancel-previous-runs:
@@ -43,10 +44,26 @@ jobs:
       - name: Run Cargo.toml linter
         run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint
 
+  check-rustc:
+    needs:
+      - cancel-previous-runs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check rustc version
+        run: |
+          # Check rustc version, log message and exit if it doesnt match env 
+          CURRENT_RUSTC_VERSION=$(rustc --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+          if [ "$CURRENT_RUSTC_VERSION" != "$RUSTC_VERSION" ]; then
+            echo "Rustc version ($CURRENT_RUSTC_VERSION) does not match the required version ($RUSTC_VERSION)"
+            exit 1 
+          fi
+          echo "Rustc version ($CURRENT_RUSTC_VERSION) matches the required version ($RUSTC_VERSION)"
+
   get-workspace-members:
     needs:
       - cancel-previous-runs
       - cargo-toml-fmt-check
+      - check-rustc
     runs-on: ubuntu-latest
     outputs:
       members: ${{ steps.set-members.outputs.members }}
@@ -64,6 +81,7 @@ jobs:
   mdbook-build:
     needs:
       - cancel-previous-runs
+      - check-rustc
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -131,6 +149,7 @@ jobs:
     needs:
       - cancel-previous-runs
       - cargo-toml-fmt-check
+      - check-rustc
     runs-on: ubuntu-latest
     services:
       postgres:
@@ -307,6 +326,7 @@ jobs:
   publish-docker-image:
     needs:
       - cancel-previous-runs
+      - check-rustc
     if: github.event_name == 'release' || github.event.action == 'published' || github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     permissions:
